import { VlmSettings } from "@/types/vlm";

export const DEFAULT_VLM_SETTINGS: VlmSettings = {
  mode: "remote",
  remote: {
    providerType: "openai-compatible",
    baseUrl: "https://api.example.com/v1/chat/completions",
    modelId: "gpt-4o-mini",
    apiVersion: "",
    hfProvider: "",
    authScheme: "bearer",
    authHeaderName: "Authorization",
    apiKey: "",
    extraHeaders: [],
    requestTimeoutMs: 30000,
    proxyUrl: "",
    corsMode: "cors",
    healthCheckPath: "/health",
    capabilities: {
      chat: true,
      textGeneration: true,
      embeddings: false,
      vision: true,
      functionCalling: true,
      streamingSupport: true,
      batching: false,
      responseFormat: "text",
      maxContextTokens: 128000,
    },
    defaults: {
      systemPrompt: "",
      temperature: 0.2,
      topP: 1,
      topK: 40,
      repetitionPenalty: 1,
      stopSequences: [],
      maxOutputTokens: 1024,
      seed: null,
      streaming: true,
      jsonMode: false,
      toolInvocation: "auto",
      jsonSchema: "",
    },
    rateLimits: {
      rpm: 60,
      tpm: 90000,
      concurrency: 5,
    },
    retryPolicy: {
      maxRetries: 2,
      strategy: "exponential",
      initialDelayMs: 1000,
    },
    circuitBreaker: {
      failureThreshold: 5,
      windowSeconds: 60,
      resetSeconds: 30,
    },
    parameterMapping: {
      bodyTemplate:
        '{"model":"{{model}}","messages":{{messages}},"temperature":{{temperature}},"max_tokens":{{maxTokens}}}',
      responseTextPath: "choices[0].message.content",
      promptTokensPath: "usage.prompt_tokens",
      completionTokensPath: "usage.completion_tokens",
      totalTokensPath: "usage.total_tokens",
      finishReasonPath: "choices[0].finish_reason",
      toolCallPath: "choices[0].message.tool_calls",
    },
    logging: {
      promptLogging: "redacted",
      piiRedaction: true,
      persistResponses: "24h",
      dataResidencyNote: "Data processed in provider region.",
      costTracking: {
        inputPrice: 0,
        outputPrice: 0,
        currency: "USD",
      },
    },
    ocr: {
      inputLimitChars: 12000,
      chunkingStrategy: "tokens",
      imageHandling: "upload",
      maxImageSizeMb: 25,
      allowedImageFormats: "jpg,jpeg,png,webp",
      layoutJsonExpected: false,
      postProcessingTemplate: "",
    },
  },
  local: {
    modelId: "Qwen/Qwen3-VL-2B-Instruct",
    dtype: "auto",
    deviceMap: "auto",
    maxNewTokens: 512,
    enableFlashAttention2: false,
  },
};
